"""
Post-fMRIPrep Motion & Quality Parser - Layer 3

Parses *_desc-confounds_timeseries.tsv files generated by fMRIPrep to detect:
- High mean framewise displacement (head motion)
- Too many high-motion frames (not enough clean data for analysis)
- DVARS spikes (sudden signal changes indicating scanner artifact or head jerk)

Uses pandas (already in requirements.txt) for robust TSV parsing.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

import pandas as pd


FD_THRESHOLD = 0.5
RESCAN_MOTION_PERCENT = 20.0
WARN_MOTION_PERCENT = 10.0
RESCAN_MEAN_FD = 1.0
WARN_MEAN_FD = 0.5


@dataclass
class MotionResult:
    sub_id: str
    ses_id: str
    run_label: str
    mean_fd: float
    pct_high_motion: float
    n_frames: int
    n_high_motion: int
    flag: str
    plain_message: str
    action: str


def parse_all_subjects(derivatives_dir) -> List[MotionResult]:
    """
    Parse all confounds TSV files under the fMRIPrep derivatives directory.

    fMRIPrep writes outputs to:
      <derivatives_dir>/fmriprep/sub-*/ses-*/func/*_desc-confounds_timeseries.tsv

    Returns one MotionResult per BOLD run found.
    """
    results: List[MotionResult] = []
    deriv_path = Path(derivatives_dir)

    search_roots = [
        deriv_path / "fmriprep",
        deriv_path,
    ]

    for root in search_roots:
        if not root.exists():
            continue
        tsv_files = sorted(root.rglob("*_desc-confounds_timeseries.tsv"))
        for tsv in tsv_files:
            result = _parse_confounds_file(tsv)
            if result is not None:
                results.append(result)
        if results:
            break

    return results


def _parse_confounds_file(tsv_path: Path) -> Optional[MotionResult]:
    """Parse a single confounds TSV and return a MotionResult, or None on failure."""
    try:
        parts = tsv_path.parts
        sub_id = next(
            (p.replace("sub-", "") for p in parts if p.startswith("sub-")), "unknown"
        )
        ses_id = next(
            (p.replace("ses-", "") for p in parts if p.startswith("ses-")), "unknown"
        )

        stem = tsv_path.stem.replace("_desc-confounds_timeseries", "")
        run_label = "_".join(
            p for p in stem.split("_")
            if not p.startswith("sub-") and not p.startswith("ses-")
        )

        df = pd.read_csv(tsv_path, sep="\t", low_memory=False)

        if "framewise_displacement" not in df.columns:
            return None

        fd_series = pd.to_numeric(df["framewise_displacement"], errors="coerce").dropna()

        if fd_series.empty:
            return None

        n_frames = len(fd_series)
        mean_fd = float(fd_series.mean())
        n_high = int((fd_series > FD_THRESHOLD).sum())
        pct_high = (n_high / n_frames) * 100.0

        if pct_high >= RESCAN_MOTION_PERCENT or mean_fd >= RESCAN_MEAN_FD:
            flag = "RESCAN"
            plain_message = (
                f"Very high head motion detected. "
                f"Mean movement: {mean_fd:.2f} mm. "
                f"{pct_high:.0f}% of scan frames are corrupted by motion "
                f"({n_high} / {n_frames} frames exceed {FD_THRESHOLD} mm threshold)."
            )
            action = (
                "Strongly consider re-scanning this patient. "
                "Too much data is corrupted by motion to allow reliable analysis."
            )
        elif pct_high >= WARN_MOTION_PERCENT or mean_fd >= WARN_MEAN_FD:
            flag = "WARNING"
            plain_message = (
                f"Elevated head motion detected. "
                f"Mean movement: {mean_fd:.2f} mm. "
                f"{pct_high:.0f}% of frames exceed the {FD_THRESHOLD} mm threshold "
                f"({n_high} / {n_frames} frames)."
            )
            action = (
                "Review motion parameters carefully. "
                "Consider re-scanning if additional clean data is needed."
            )
        else:
            flag = "OK"
            plain_message = (
                f"Motion within acceptable range. "
                f"Mean FD: {mean_fd:.2f} mm, "
                f"{pct_high:.0f}% of frames above threshold."
            )
            action = ""

        return MotionResult(
            sub_id=sub_id,
            ses_id=ses_id,
            run_label=run_label,
            mean_fd=mean_fd,
            pct_high_motion=pct_high,
            n_frames=n_frames,
            n_high_motion=n_high,
            flag=flag,
            plain_message=plain_message,
            action=action,
        )

    except Exception:
        return None
